#端口号
server:
  port: 8011

#数据库连接配置
spring:
  datasource:
    username: root
    password: Sql123
    url: jdbc:mysql://localhost:3306/vueblog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

  #配置日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


  #配置逻辑删除
  #mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379
bwy:
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token有效时长，7天，单位秒
    expire: 604800
    header: token
